name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install
    - name: Run lint
      run: bundle exec rubocop
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install
    - name: Run specs
      run: bundle exec rspec
